/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EntryId = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FlightLog {
  'id' : LogId,
  'completedAt' : bigint,
  'playerId' : PlayerId,
  'score' : ScoreBreakdown,
  'plane' : Plane,
  'weather' : Weather,
  'planName' : string,
}
export interface FlightLogView {
  'id' : LogId,
  'completedAt' : bigint,
  'playerId' : PlayerId,
  'score' : ScoreBreakdown,
  'plane' : Plane,
  'weather' : Weather,
  'planName' : string,
}
export interface FlightPlan {
  'id' : PlanId,
  'routeDescription' : string,
  'name' : string,
  'waypoint' : Waypoint,
  'plane' : Plane__2,
  'weather' : Weather,
  'departure' : Runway,
  'landing' : Runway,
}
export interface LeaderboardEntry {
  'id' : EntryId,
  'total' : bigint,
  'displayName' : string,
  'playerId' : Principal,
  'submittedAt' : bigint,
  'plane' : Plane,
  'weather' : Weather,
  'planName' : string,
}
export interface LeaderboardEntryView {
  'id' : EntryId,
  'total' : bigint,
  'displayName' : string,
  'playerId' : Principal,
  'submittedAt' : bigint,
  'plane' : Plane,
  'weather' : Weather,
  'planName' : string,
}
export type LogId = bigint;
export type PlanId = bigint;
export type Plane = { 'cessna' : null } |
  { 'gulfstream' : null };
export type PlaneId = bigint;
export interface Plane__2 {
  'id' : PlaneId,
  'name' : string,
  'handling' : string,
}
export type PlayerId = Principal;
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface Runway { 'name' : string, 'description' : string }
export interface ScoreBreakdown {
  'landingSmoothness' : bigint,
  'total' : bigint,
  'speed' : bigint,
}
export type SubmitOutcome = { 'tooLow' : { 'needed' : bigint } } |
  { 'unchanged' : LeaderboardEntryView } |
  { 'improved' : LeaderboardEntryView } |
  { 'posted' : LeaderboardEntryView };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Waypoint { 'name' : string, 'description' : string }
export type Weather = { 'nighttime' : null } |
  { 'partlyCloudy' : null } |
  { 'daytime' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__flightLogs' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<FlightLog>
  >,
  '__leaderboard' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<LeaderboardEntry>
  >,
  '__nextLeaderboardId' : ActorMethod<[], any>,
  '__nextLogId' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFlightLog' : ActorMethod<[LogId], [] | [FlightLogView]>,
  'getFlightPlan' : ActorMethod<[PlanId], [] | [FlightPlan]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFlightLogs' : ActorMethod<[], Array<FlightLogView>>,
  'listFlightPlans' : ActorMethod<[], Array<FlightPlan>>,
  'listLeaderboard' : ActorMethod<[], Array<LeaderboardEntryView>>,
  'listPlanes' : ActorMethod<[], Array<Plane__2>>,
  'listWeather' : ActorMethod<[], Array<Weather>>,
  'recordFlightLog' : ActorMethod<
    [bigint, string, Plane, Weather, ScoreBreakdown],
    FlightLogView
  >,
  'submitLeaderboardScore' : ActorMethod<
    [string, string, Plane, Weather, bigint],
    SubmitOutcome
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];