/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LogId = IDL.Nat;
export const PlayerId = IDL.Principal;
export const ScoreBreakdown = IDL.Record({
  'landingSmoothness' : IDL.Nat,
  'total' : IDL.Nat,
  'speed' : IDL.Nat,
});
export const Plane = IDL.Variant({
  'cessna' : IDL.Null,
  'gulfstream' : IDL.Null,
});
export const Weather = IDL.Variant({
  'nighttime' : IDL.Null,
  'partlyCloudy' : IDL.Null,
  'daytime' : IDL.Null,
});
export const FlightLog = IDL.Record({
  'id' : LogId,
  'completedAt' : IDL.Int,
  'playerId' : PlayerId,
  'score' : ScoreBreakdown,
  'plane' : Plane,
  'weather' : Weather,
  'planName' : IDL.Text,
});
export const EntryId = IDL.Nat;
export const LeaderboardEntry = IDL.Record({
  'id' : EntryId,
  'total' : IDL.Nat,
  'displayName' : IDL.Text,
  'playerId' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'plane' : Plane,
  'weather' : Weather,
  'planName' : IDL.Text,
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FlightLogView = IDL.Record({
  'id' : LogId,
  'completedAt' : IDL.Int,
  'playerId' : PlayerId,
  'score' : ScoreBreakdown,
  'plane' : Plane,
  'weather' : Weather,
  'planName' : IDL.Text,
});
export const PlanId = IDL.Nat;
export const Waypoint = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PlaneId = IDL.Nat;
export const Plane__2 = IDL.Record({
  'id' : PlaneId,
  'name' : IDL.Text,
  'handling' : IDL.Text,
});
export const Runway = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const FlightPlan = IDL.Record({
  'id' : PlanId,
  'routeDescription' : IDL.Text,
  'name' : IDL.Text,
  'waypoint' : Waypoint,
  'plane' : Plane__2,
  'weather' : Weather,
  'departure' : Runway,
  'landing' : Runway,
});
export const LeaderboardEntryView = IDL.Record({
  'id' : EntryId,
  'total' : IDL.Nat,
  'displayName' : IDL.Text,
  'playerId' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'plane' : Plane,
  'weather' : Weather,
  'planName' : IDL.Text,
});
export const SubmitOutcome = IDL.Variant({
  'tooLow' : IDL.Record({ 'needed' : IDL.Nat }),
  'unchanged' : LeaderboardEntryView,
  'improved' : LeaderboardEntryView,
  'posted' : LeaderboardEntryView,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__flightLogs' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(FlightLog)],
      ['query'],
    ),
  '__leaderboard' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  '__nextLeaderboardId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextLogId' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFlightLog' : IDL.Func([LogId], [IDL.Opt(FlightLogView)], ['query']),
  'getFlightPlan' : IDL.Func([PlanId], [IDL.Opt(FlightPlan)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFlightLogs' : IDL.Func([], [IDL.Vec(FlightLogView)], ['query']),
  'listFlightPlans' : IDL.Func([], [IDL.Vec(FlightPlan)], ['query']),
  'listLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntryView)], ['query']),
  'listPlanes' : IDL.Func([], [IDL.Vec(Plane__2)], ['query']),
  'listWeather' : IDL.Func([], [IDL.Vec(Weather)], ['query']),
  'recordFlightLog' : IDL.Func(
      [IDL.Int, IDL.Text, Plane, Weather, ScoreBreakdown],
      [FlightLogView],
      [],
    ),
  'submitLeaderboardScore' : IDL.Func(
      [IDL.Text, IDL.Text, Plane, Weather, IDL.Nat],
      [SubmitOutcome],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LogId = IDL.Nat;
  const PlayerId = IDL.Principal;
  const ScoreBreakdown = IDL.Record({
    'landingSmoothness' : IDL.Nat,
    'total' : IDL.Nat,
    'speed' : IDL.Nat,
  });
  const Plane = IDL.Variant({ 'cessna' : IDL.Null, 'gulfstream' : IDL.Null });
  const Weather = IDL.Variant({
    'nighttime' : IDL.Null,
    'partlyCloudy' : IDL.Null,
    'daytime' : IDL.Null,
  });
  const FlightLog = IDL.Record({
    'id' : LogId,
    'completedAt' : IDL.Int,
    'playerId' : PlayerId,
    'score' : ScoreBreakdown,
    'plane' : Plane,
    'weather' : Weather,
    'planName' : IDL.Text,
  });
  const EntryId = IDL.Nat;
  const LeaderboardEntry = IDL.Record({
    'id' : EntryId,
    'total' : IDL.Nat,
    'displayName' : IDL.Text,
    'playerId' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'plane' : Plane,
    'weather' : Weather,
    'planName' : IDL.Text,
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FlightLogView = IDL.Record({
    'id' : LogId,
    'completedAt' : IDL.Int,
    'playerId' : PlayerId,
    'score' : ScoreBreakdown,
    'plane' : Plane,
    'weather' : Weather,
    'planName' : IDL.Text,
  });
  const PlanId = IDL.Nat;
  const Waypoint = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const PlaneId = IDL.Nat;
  const Plane__2 = IDL.Record({
    'id' : PlaneId,
    'name' : IDL.Text,
    'handling' : IDL.Text,
  });
  const Runway = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const FlightPlan = IDL.Record({
    'id' : PlanId,
    'routeDescription' : IDL.Text,
    'name' : IDL.Text,
    'waypoint' : Waypoint,
    'plane' : Plane__2,
    'weather' : Weather,
    'departure' : Runway,
    'landing' : Runway,
  });
  const LeaderboardEntryView = IDL.Record({
    'id' : EntryId,
    'total' : IDL.Nat,
    'displayName' : IDL.Text,
    'playerId' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'plane' : Plane,
    'weather' : Weather,
    'planName' : IDL.Text,
  });
  const SubmitOutcome = IDL.Variant({
    'tooLow' : IDL.Record({ 'needed' : IDL.Nat }),
    'unchanged' : LeaderboardEntryView,
    'improved' : LeaderboardEntryView,
    'posted' : LeaderboardEntryView,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__flightLogs' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(FlightLog)],
        ['query'],
      ),
    '__leaderboard' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    '__nextLeaderboardId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextLogId' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFlightLog' : IDL.Func([LogId], [IDL.Opt(FlightLogView)], ['query']),
    'getFlightPlan' : IDL.Func([PlanId], [IDL.Opt(FlightPlan)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFlightLogs' : IDL.Func([], [IDL.Vec(FlightLogView)], ['query']),
    'listFlightPlans' : IDL.Func([], [IDL.Vec(FlightPlan)], ['query']),
    'listLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntryView)],
        ['query'],
      ),
    'listPlanes' : IDL.Func([], [IDL.Vec(Plane__2)], ['query']),
    'listWeather' : IDL.Func([], [IDL.Vec(Weather)], ['query']),
    'recordFlightLog' : IDL.Func(
        [IDL.Int, IDL.Text, Plane, Weather, ScoreBreakdown],
        [FlightLogView],
        [],
      ),
    'submitLeaderboardScore' : IDL.Func(
        [IDL.Text, IDL.Text, Plane, Weather, IDL.Nat],
        [SubmitOutcome],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };