/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface ScoreBreakdown {
    landingSmoothness: bigint;
    total: bigint;
    speed: bigint;
}
export interface LeaderboardEntryView {
    id: EntryId;
    total: bigint;
    displayName: string;
    playerId: Principal;
    submittedAt: bigint;
    plane: Plane;
    weather: Weather;
    planName: string;
}
export interface LeaderboardEntry {
    id: EntryId;
    total: bigint;
    displayName: string;
    playerId: Principal;
    submittedAt: bigint;
    plane: Plane;
    weather: Weather;
    planName: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type PlaneId = bigint;
export interface FlightLog {
    id: LogId;
    completedAt: bigint;
    playerId: PlayerId;
    score: ScoreBreakdown;
    plane: Plane;
    weather: Weather;
    planName: string;
}
export interface Waypoint {
    name: string;
    description: string;
}
export type LogId = bigint;
export interface Plane__2 {
    id: PlaneId;
    name: string;
    handling: string;
}
export type PlayerId = Principal;
export interface FlightPlan {
    id: PlanId;
    routeDescription: string;
    name: string;
    waypoint: Waypoint;
    plane: Plane__2;
    weather: Weather;
    departure: Runway;
    landing: Runway;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type SubmitOutcome = {
    __kind__: "tooLow";
    tooLow: {
        needed: bigint;
    };
} | {
    __kind__: "unchanged";
    unchanged: LeaderboardEntryView;
} | {
    __kind__: "improved";
    improved: LeaderboardEntryView;
} | {
    __kind__: "posted";
    posted: LeaderboardEntryView;
};
export type EntryId = bigint;
export interface FlightLogView {
    id: LogId;
    completedAt: bigint;
    playerId: PlayerId;
    score: ScoreBreakdown;
    plane: Plane;
    weather: Weather;
    planName: string;
}
export interface Runway {
    name: string;
    description: string;
}
export type PlanId = bigint;
export enum Plane {
    cessna = "cessna",
    gulfstream = "gulfstream"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Weather {
    nighttime = "nighttime",
    partlyCloudy = "partlyCloudy",
    daytime = "daytime"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __flightLogs(io: bigint | null, count: bigint | null): Promise<Array<FlightLog>>;
    __leaderboard(io: bigint | null, count: bigint | null): Promise<Array<LeaderboardEntry>>;
    __nextLeaderboardId(): Promise<any>;
    __nextLogId(): Promise<any>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getFlightLog(logId: LogId): Promise<FlightLogView | null>;
    getFlightPlan(planId: PlanId): Promise<FlightPlan | null>;
    isCallerAdmin(): Promise<boolean>;
    listFlightLogs(): Promise<Array<FlightLogView>>;
    listFlightPlans(): Promise<Array<FlightPlan>>;
    listLeaderboard(): Promise<Array<LeaderboardEntryView>>;
    listPlanes(): Promise<Array<Plane__2>>;
    listWeather(): Promise<Array<Weather>>;
    recordFlightLog(completedAt: bigint, planName: string, plane: Plane, weather: Weather, score: ScoreBreakdown): Promise<FlightLogView>;
    submitLeaderboardScore(displayName: string, planName: string, plane: Plane, weather: Weather, total: bigint): Promise<SubmitOutcome>;
}
import type { EntryId as _EntryId, Error as _Error, FlightLog as _FlightLog, FlightLogView as _FlightLogView, FlightPlan as _FlightPlan, LeaderboardEntry as _LeaderboardEntry, LeaderboardEntryView as _LeaderboardEntryView, LogId as _LogId, PlanId as _PlanId, Plane as _Plane, Plane__2 as _Plane__2, PlayerId as _PlayerId, Result as _Result, Runway as _Runway, ScoreBreakdown as _ScoreBreakdown, SubmitOutcome as _SubmitOutcome, UserRole as _UserRole, Waypoint as _Waypoint, Weather as _Weather } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __flightLogs(arg0: bigint | null, arg1: bigint | null): Promise<Array<FlightLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.__flightLogs(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__flightLogs(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __leaderboard(arg0: bigint | null, arg1: bigint | null): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.__leaderboard(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__leaderboard(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async __nextLeaderboardId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextLeaderboardId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextLeaderboardId();
            return result;
        }
    }
    async __nextLogId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextLogId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextLogId();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlightLog(arg0: LogId): Promise<FlightLogView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightLog(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightLog(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlightPlan(arg0: PlanId): Promise<FlightPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightPlan(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightPlan(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFlightLogs(): Promise<Array<FlightLogView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFlightLogs();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFlightLogs();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFlightPlans(): Promise<Array<FlightPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFlightPlans();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFlightPlans();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeaderboard(): Promise<Array<LeaderboardEntryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeaderboard();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeaderboard();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPlanes(): Promise<Array<Plane__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlanes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlanes();
            return result;
        }
    }
    async listWeather(): Promise<Array<Weather>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWeather();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWeather();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordFlightLog(arg0: bigint, arg1: string, arg2: Plane, arg3: Weather, arg4: ScoreBreakdown): Promise<FlightLogView> {
        if (this.processError) {
            try {
                const result = await this.actor.recordFlightLog(arg0, arg1, to_candid_Plane_n30(this._uploadFile, this._downloadFile, arg2), to_candid_Weather_n32(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_FlightLogView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordFlightLog(arg0, arg1, to_candid_Plane_n30(this._uploadFile, this._downloadFile, arg2), to_candid_Weather_n32(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_FlightLogView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLeaderboardScore(arg0: string, arg1: string, arg2: Plane, arg3: Weather, arg4: bigint): Promise<SubmitOutcome> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeaderboardScore(arg0, arg1, to_candid_Plane_n30(this._uploadFile, this._downloadFile, arg2), to_candid_Weather_n32(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_SubmitOutcome_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeaderboardScore(arg0, arg1, to_candid_Plane_n30(this._uploadFile, this._downloadFile, arg2), to_candid_Weather_n32(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_SubmitOutcome_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Error_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_FlightLogView_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightLogView): FlightLogView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FlightLog_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightLog): FlightLog {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FlightPlan_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightPlan): FlightPlan {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntryView_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntryView): LeaderboardEntryView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Plane_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Plane): Plane {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitOutcome_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitOutcome): SubmitOutcome {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Weather_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Weather): Weather {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlightLogView]): FlightLogView | null {
    return value.length === 0 ? null : from_candid_FlightLogView_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlightPlan]): FlightPlan | null {
    return value.length === 0 ? null : from_candid_FlightPlan_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    total: bigint;
    displayName: string;
    playerId: Principal;
    submittedAt: bigint;
    plane: _Plane;
    weather: _Weather;
    planName: string;
}): {
    id: EntryId;
    total: bigint;
    displayName: string;
    playerId: Principal;
    submittedAt: bigint;
    plane: Plane;
    weather: Weather;
    planName: string;
} {
    return {
        id: value.id,
        total: value.total,
        displayName: value.displayName,
        playerId: value.playerId,
        submittedAt: value.submittedAt,
        plane: from_candid_Plane_n5(_uploadFile, _downloadFile, value.plane),
        weather: from_candid_Weather_n7(_uploadFile, _downloadFile, value.weather),
        planName: value.planName
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlanId;
    routeDescription: string;
    name: string;
    waypoint: _Waypoint;
    plane: _Plane__2;
    weather: _Weather;
    departure: _Runway;
    landing: _Runway;
}): {
    id: PlanId;
    routeDescription: string;
    name: string;
    waypoint: Waypoint;
    plane: Plane__2;
    weather: Weather;
    departure: Runway;
    landing: Runway;
} {
    return {
        id: value.id,
        routeDescription: value.routeDescription,
        name: value.name,
        waypoint: value.waypoint,
        plane: value.plane,
        weather: from_candid_Weather_n7(_uploadFile, _downloadFile, value.weather),
        departure: value.departure,
        landing: value.landing
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LogId;
    completedAt: bigint;
    playerId: _PlayerId;
    score: _ScoreBreakdown;
    plane: _Plane;
    weather: _Weather;
    planName: string;
}): {
    id: LogId;
    completedAt: bigint;
    playerId: PlayerId;
    score: ScoreBreakdown;
    plane: Plane;
    weather: Weather;
    planName: string;
} {
    return {
        id: value.id,
        completedAt: value.completedAt,
        playerId: value.playerId,
        score: value.score,
        plane: from_candid_Plane_n5(_uploadFile, _downloadFile, value.plane),
        weather: from_candid_Weather_n7(_uploadFile, _downloadFile, value.weather),
        planName: value.planName
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tooLow: {
        needed: bigint;
    };
} | {
    unchanged: _LeaderboardEntryView;
} | {
    improved: _LeaderboardEntryView;
} | {
    posted: _LeaderboardEntryView;
}): {
    __kind__: "tooLow";
    tooLow: {
        needed: bigint;
    };
} | {
    __kind__: "unchanged";
    unchanged: LeaderboardEntryView;
} | {
    __kind__: "improved";
    improved: LeaderboardEntryView;
} | {
    __kind__: "posted";
    posted: LeaderboardEntryView;
} {
    return "tooLow" in value ? {
        __kind__: "tooLow",
        tooLow: value.tooLow
    } : "unchanged" in value ? {
        __kind__: "unchanged",
        unchanged: from_candid_LeaderboardEntryView_n28(_uploadFile, _downloadFile, value.unchanged)
    } : "improved" in value ? {
        __kind__: "improved",
        improved: from_candid_LeaderboardEntryView_n28(_uploadFile, _downloadFile, value.improved)
    } : "posted" in value ? {
        __kind__: "posted",
        posted: from_candid_LeaderboardEntryView_n28(_uploadFile, _downloadFile, value.posted)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cessna: null;
} | {
    gulfstream: null;
}): Plane {
    return "cessna" in value ? Plane.cessna : "gulfstream" in value ? Plane.gulfstream : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nighttime: null;
} | {
    partlyCloudy: null;
} | {
    daytime: null;
}): Weather {
    return "nighttime" in value ? Weather.nighttime : "partlyCloudy" in value ? Weather.partlyCloudy : "daytime" in value ? Weather.daytime : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlightLog>): Array<FlightLog> {
    return value.map((x)=>from_candid_FlightLog_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlightLogView>): Array<FlightLogView> {
    return value.map((x)=>from_candid_FlightLogView_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlightPlan>): Array<FlightPlan> {
    return value.map((x)=>from_candid_FlightPlan_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntryView>): Array<LeaderboardEntryView> {
    return value.map((x)=>from_candid_LeaderboardEntryView_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Weather>): Array<Weather> {
    return value.map((x)=>from_candid_Weather_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Plane_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plane): _Plane {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Weather_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Weather): _Weather {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plane): {
    cessna: null;
} | {
    gulfstream: null;
} {
    return value == Plane.cessna ? {
        cessna: null
    } : value == Plane.gulfstream ? {
        gulfstream: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Weather): {
    nighttime: null;
} | {
    partlyCloudy: null;
} | {
    daytime: null;
} {
    return value == Weather.nighttime ? {
        nighttime: null
    } : value == Weather.partlyCloudy ? {
        partlyCloudy: null
    } : value == Weather.daytime ? {
        daytime: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
